In [1]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

In [2]:
X, y = fetch_california_housing(return_X_y=True, as_frame=True)

In [3]:
X.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [4]:
# equal-width bins
X["HouseAge_binned"] = pd.cut(X["HouseAge"], bins=5)

X["HouseAge_custom_binned"] = pd.cut(X["HouseAge"], bins=[0, 5, 10, 20, 50, 100])

# equal-frequency bins
X["MedInc_binned"] = pd.qcut(X["MedInc"], q=3, labels=["low", "mid", "high"])

X[["HouseAge", "HouseAge_binned", "HouseAge_custom_binned","MedInc", "MedInc_binned"]].head()

   HouseAge HouseAge_binned HouseAge_custom_binned  MedInc MedInc_binned
0      41.0    (31.6, 41.8]               (20, 50]  8.3252          high
1      21.0    (11.2, 21.4]               (20, 50]  8.3014          high
2      52.0    (41.8, 52.0]              (50, 100]  7.2574          high
3      52.0    (41.8, 52.0]              (50, 100]  5.6431          high
4      52.0    (41.8, 52.0]              (50, 100]  3.8462           mid

In [5]:
X["MedInc_binned"].value_counts()

MedInc_binned
mid     6881
low     6880
high    6879
Name: count, dtype: int64

In [6]:
X["HouseAge_binned"].value_counts()

HouseAge_binned
(31.6, 41.8]     5455
(11.2, 21.4]     4916
(21.4, 31.6]     4864
(41.8, 52.0]     3582
(0.949, 11.2]    1823
Name: count, dtype: int64

In [7]:
agg = X.groupby("MedInc_binned")["AveRooms"].agg(["sum", "mean", "count"])
agg.columns = ["total_rooms", "avg_rooms", "num_houses"]

agg.head()

                total_rooms  avg_rooms  num_houses
MedInc_binned
low            31931.391119   4.641191        6880
mid            36344.763176   5.281901        6881
high           43778.400384   6.364065        6879

In [8]:
X = X.merge(agg, on="MedInc_binned", how="left")

X.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,HouseAge_binned,HouseAge_custom_binned,MedInc_binned,total_rooms,avg_rooms,num_houses
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,"(31.6, 41.8]","(20, 50]",high,43778.400384,6.364065,6879
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,"(11.2, 21.4]","(20, 50]",high,43778.400384,6.364065,6879
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,"(41.8, 52.0]","(50, 100]",high,43778.400384,6.364065,6879
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,"(41.8, 52.0]","(50, 100]",high,43778.400384,6.364065,6879
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,"(41.8, 52.0]","(50, 100]",mid,36344.763176,5.281901,6881